#!/bin/sh
set -e
if [ "$1" = purge ] && command -v deb-systemd-helper >/dev/null; then
    deb-systemd-helper --user purge unproxy.service >/dev/null || true
    deb-systemd-helper --user unmask unproxy.service >/dev/null || true
fi
