#!/bin/sh
set -eu
console_user=$(/usr/bin/stat -f %Su /dev/console)
if [ "$console_user" != root ] && [ "$console_user" != loginwindow ]; then
    uid=$(/usr/bin/id -u "$console_user")
    /bin/launchctl enable "gui/$uid/de.m42e.unproxy"
    /bin/launchctl bootstrap "gui/$uid" /Library/LaunchAgents/de.m42e.unproxy.plist
fi
